# Generated by Django 5.1 on 2025-04-05 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='phone_number',
            new_name='phone_no',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='account/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
